application:
  updateCheck: 300000
  timeOut: 10000
  appName: LLB EUR Rate Monitor
  userAgent: Mozilla
  country: EWU

#logging.level.org.hibernate: DEBUG
#logging.leve.com.zaxxer.hikari: DEBUG

---
spring:
  config:
    activate:
      on-profile: default
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:${user.home}/data/dbs/ratemonitor.hsqldb

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3306/ratemonitor
    username: ratemonitor
    password: ratemonitor